"""added last table

Revision ID: db829bb1e368
Revises: aca0dcfc8fa4
Create Date: 2021-10-10 11:35:48.413657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db829bb1e368'
down_revision = 'aca0dcfc8fa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ink_on_canvases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ink_id', sa.Integer(), nullable=False),
    sa.Column('canvas_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['canvas_id'], ['canvases.id'], ),
    sa.ForeignKeyConstraint(['ink_id'], ['inks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('canvases', sa.Column('private_canvas', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('canvases', 'private_canvas')
    op.drop_table('ink_on_canvases')
    # ### end Alembic commands ###
