"""empty message

Revision ID: adb00d872582
Revises: 3df9815cf61a
Create Date: 2021-10-13 14:40:15.352814

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'adb00d872582'
down_revision = '3df9815cf61a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inks_on_canvases',
    sa.Column('ink_id', sa.Integer(), nullable=False),
    sa.Column('canvas_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['canvas_id'], ['canvases.id'], ),
    sa.ForeignKeyConstraint(['ink_id'], ['inks.id'], ),
    sa.PrimaryKeyConstraint('ink_id', 'canvas_id')
    )
    op.drop_table('ink_on_canvases')
    op.alter_column('follows', 'follower_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('follows', 'followed_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('follows', 'id')
    op.drop_column('follows', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follows', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('follows', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('follows', 'followed_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('follows', 'follower_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('ink_on_canvases',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ink_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('canvas_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['canvas_id'], ['canvases.id'], name='ink_on_canvases_canvas_id_fkey'),
    sa.ForeignKeyConstraint(['ink_id'], ['inks.id'], name='ink_on_canvases_ink_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ink_on_canvases_pkey')
    )
    op.drop_table('inks_on_canvases')
    # ### end Alembic commands ###
