"""empty message

Revision ID: 3df9815cf61a
Revises: db829bb1e368
Create Date: 2021-10-13 13:14:39.694565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3df9815cf61a'
down_revision = 'db829bb1e368'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ink_categories',
    sa.Column('ink_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['ink_id'], ['inks.id'], ),
    sa.PrimaryKeyConstraint('ink_id', 'category_id')
    )
    op.drop_constraint('inks_category_1_fkey', 'inks', type_='foreignkey')
    op.drop_constraint('inks_category_2_fkey', 'inks', type_='foreignkey')
    op.drop_constraint('inks_category_3_fkey', 'inks', type_='foreignkey')
    op.drop_column('inks', 'category_1')
    op.drop_column('inks', 'category_3')
    op.drop_column('inks', 'category_2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inks', sa.Column('category_2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('inks', sa.Column('category_3', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('inks', sa.Column('category_1', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('inks_category_3_fkey', 'inks', 'categories', ['category_3'], ['id'])
    op.create_foreign_key('inks_category_2_fkey', 'inks', 'categories', ['category_2'], ['id'])
    op.create_foreign_key('inks_category_1_fkey', 'inks', 'categories', ['category_1'], ['id'])
    op.drop_table('ink_categories')
    # ### end Alembic commands ###
