"""empty message

Revision ID: 8658d4ccb931
Revises: ebc4901391dd
Create Date: 2021-10-13 17:31:25.572485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8658d4ccb931'
down_revision = 'ebc4901391dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inks', sa.Column('creator_username', sa.String(), nullable=False))
    op.create_foreign_key(None, 'inks', 'users', ['creator_username'], ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inks', type_='foreignkey')
    op.drop_column('inks', 'creator_username')
    # ### end Alembic commands ###
