"""added more tables

Revision ID: aca0dcfc8fa4
Revises: 81bf27e93357
Create Date: 2021-10-10 11:25:54.678664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aca0dcfc8fa4'
down_revision = '81bf27e93357'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('canvases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=2000), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('subtitle', sa.String(length=500), nullable=True),
    sa.Column('destination_link', sa.String(length=2000), nullable=True),
    sa.Column('category_1', sa.Integer(), nullable=True),
    sa.Column('category_2', sa.Integer(), nullable=True),
    sa.Column('category_3', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_1'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['category_2'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['category_3'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inks')
    op.drop_table('canvases')
    op.drop_table('categories')
    # ### end Alembic commands ###
