"""empty message

Revision ID: ebc4901391dd
Revises: 7b9b80c60d9d
Create Date: 2021-10-13 16:29:38.995192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebc4901391dd'
down_revision = '7b9b80c60d9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follows', sa.Column('followed_id', sa.Integer(), nullable=True))
    op.drop_constraint('follows_following_id_fkey', 'follows', type_='foreignkey')
    op.create_foreign_key(None, 'follows', 'users', ['followed_id'], ['id'])
    op.drop_column('follows', 'following_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follows', sa.Column('following_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'follows', type_='foreignkey')
    op.create_foreign_key('follows_following_id_fkey', 'follows', 'users', ['following_id'], ['id'])
    op.drop_column('follows', 'followed_id')
    # ### end Alembic commands ###
